name: Playwright Tests Actions Sample
on:
  push:
    branches: [ main, master, release/* ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: "0 2 * * 1-5"
  workflow_dispatch:
  
jobs:
  test:
    timeout-minutes: 60
    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx run test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
